# Ticket classification

## Starting

Import the necessary libraries

In [43]:
import pandas as pd
import numpy as np

Call your data

In [44]:
#data = pd.read_csv('generated_tickets_csv.csv')
data = pd.read_csv('Tickets data collection.csv')

Check your data

What do you think we really need to use in our model?

In [45]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Timestamp              167 non-null    str
 1   Title of your ticket   193 non-null    str
 2   Write your ticket      194 non-null    str
 3   Your ticket is about:  195 non-null    str
dtypes: str(4)
memory usage: 6.2 KB

In [46]:
# Change the name of the columns to: Timestam, Title, Description and Class
data

,Timestamp,Title of your ticket,Write your ticket,Your ticket is about:
0,2023/10/10 12:36:43 pm EEST,Employee Data Access Request,An employee has requested access to their pers...,Privacy issue
1,2023/10/10 12:37:18 pm EEST,Request for New Monitors,We need to purchase 10 new high-resolution mon...,Purchase requisition
2,2023/10/10 1:51:10 pm EEST,Email Client Crashing,Our email client is frequently crashing on sta...,Software issue
3,2023/10/10 1:51:44 pm EEST,Slow File-Sharing Server,The company's file-sharing server is experienc...,Software issue
4,2023/10/10 1:52:43 pm EEST,Software License Procurement,We need to purchase a new software license for...,Purchase requisition
...,...,...,...,...
190,NaN,Customer Data Deletion Request,NaN,Privacy issue
191,NaN,Privacy Policy Update,Our privacy policy needs to be updated to refl...,Privacy issue
192,NaN,Vendor Data Handling Assessment,Assess how our vendors handle our data and ens...,Privacy issue
193,NaN,Privacy Impact Assessment,Conduct a Privacy Impact Assessment (PIA) for ...,Privacy issue
194,NaN,Incident Response Plan Review,Review and update our privacy incident respons...,Privacy issue

**What we need to do?**

- Check that we have one missing title and one missing ticket content. What we should do?
- What we can do for the missing Timestamps? 
- Which information we need?
- Always keep in mind our goal.

## Data Processing

In [47]:
data.loc[[72]]

,Timestamp,Title of your ticket,Write your ticket,Your ticket is about:
72,2024/10/11 11:44:18 am EEST,The printer doesnt work anymore.,"When I try to print from my computer, i get th...",Software issue

In [48]:
#Give a title for the ticket
data.columns = ['Time', 'Title', 'Description', 'Class']
data.loc[:0]

,Time,Title,Description,Class
0,2023/10/10 12:36:43 pm EEST,Employee Data Access Request,An employee has requested access to their pers...,Privacy issue

In [49]:
data.loc[[72]]

,Time,Title,Description,Class
72,2024/10/11 11:44:18 am EEST,The printer doesnt work anymore.,"When I try to print from my computer, i get th...",Software issue

In [50]:
#What to do with the missing ticket?
data = data.dropna(subset=['Description'])
data = data.drop(columns='Time')
data.info()

<class 'pandas.DataFrame'>
Index: 194 entries, 0 to 194
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        192 non-null    str
 1   Description  194 non-null    str
 2   Class        194 non-null    str
dtypes: str(3)
memory usage: 6.1 KB

In [51]:
#join the title with the ticket description
data['Title'] = data['Title'].fillna(data['Description'])
data.info()

<class 'pandas.DataFrame'>
Index: 194 entries, 0 to 194
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        194 non-null    str
 1   Description  194 non-null    str
 2   Class        194 non-null    str
dtypes: str(3)
memory usage: 6.1 KB

In [53]:
#Concat because we need one tekst and one target
data['TitleDesc'] = data['Title'] + ' ' + data['Description']
data

,Title,Description,Class,TitleDesc
0,Employee Data Access Request,An employee has requested access to their pers...,Privacy issue,Employee Data Access Request An employee has r...
1,Request for New Monitors,We need to purchase 10 new high-resolution mon...,Purchase requisition,Request for New Monitors We need to purchase 1...
2,Email Client Crashing,Our email client is frequently crashing on sta...,Software issue,Email Client Crashing Our email client is freq...
3,Slow File-Sharing Server,The company's file-sharing server is experienc...,Software issue,Slow File-Sharing Server The company's file-sh...
4,Software License Procurement,We need to purchase a new software license for...,Purchase requisition,Software License Procurement We need to purcha...
...,...,...,...,...
189,GDPR Compliance Audit,We require a comprehensive audit to ensure com...,Privacy issue,GDPR Compliance Audit We require a comprehensi...
191,Privacy Policy Update,Our privacy policy needs to be updated to refl...,Privacy issue,Privacy Policy Update Our privacy policy needs...
192,Vendor Data Handling Assessment,Assess how our vendors handle our data and ens...,Privacy issue,Vendor Data Handling Assessment Assess how our...
193,Privacy Impact Assessment,Conduct a Privacy Impact Assessment (PIA) for ...,Privacy issue,Privacy Impact Assessment Conduct a Privacy Im...
194,Incident Response Plan Review,Review and update our privacy incident respons...,Privacy issue,Incident Response Plan Review Review and updat...

In [54]:
data.loc[[72]]

,Title,Description,Class,TitleDesc
72,The printer doesnt work anymore.,"When I try to print from my computer, i get th...",Software issue,The printer doesnt work anymore. When I try t...

In [55]:
#Drop possible columns 
data = data.drop(columns=['Title','Description'])
data

                    Class                                          TitleDesc
0           Privacy issue  Employee Data Access Request An employee has r...
1    Purchase requisition  Request for New Monitors We need to purchase 1...
2          Software issue  Email Client Crashing Our email client is freq...
3          Software issue  Slow File-Sharing Server The company's file-sh...
4    Purchase requisition  Software License Procurement We need to purcha...
..                    ...                                                ...
189         Privacy issue  GDPR Compliance Audit We require a comprehensi...
191         Privacy issue  Privacy Policy Update Our privacy policy needs...
192         Privacy issue  Vendor Data Handling Assessment Assess how our...
193         Privacy issue  Privacy Impact Assessment Conduct a Privacy Im...
194         Privacy issue  Incident Response Plan Review Review and updat...

[194 rows x 2 columns]

In [62]:
#rename again the column to: Description
data = data.rename(columns={data.columns[1]: 'Description'})
data

                    Class                                        Description
0           Privacy issue  Employee Data Access Request An employee has r...
1    Purchase requisition  Request for New Monitors We need to purchase 1...
2          Software issue  Email Client Crashing Our email client is freq...
3          Software issue  Slow File-Sharing Server The company's file-sh...
4    Purchase requisition  Software License Procurement We need to purcha...
..                    ...                                                ...
189         Privacy issue  GDPR Compliance Audit We require a comprehensi...
191         Privacy issue  Privacy Policy Update Our privacy policy needs...
192         Privacy issue  Vendor Data Handling Assessment Assess how our...
193         Privacy issue  Privacy Impact Assessment Conduct a Privacy Im...
194         Privacy issue  Incident Response Plan Review Review and updat...

[194 rows x 2 columns]

In [63]:
X = data['Description'] 
y = data['Class']

Split your data already to be sure that no data likeage will happens

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state = 4)

In [65]:
train = pd.concat([X_train, y_train], axis =1)
train.to_csv('train_tickets.csv')

In [66]:
test = pd.concat([X_test, y_test], axis =1)
test.to_csv('test_tickets.csv')

In [67]:
train

                                           Description                 Class
76   In RGB mode stuck, lightsaber has become Hmm.....        Software issue
124  Broken pc Hey, last Thursday my pc fell to the...  Purchase requisition
5    Ergonomic Chair Purchase We're running low on ...  Purchase requisition
116  Privacy glass on the windows It would be reall...         Privacy issue
163  Request for updated design software license Th...        Software issue
..                                                 ...                   ...
104  To many places in the building with cameras I ...         Privacy issue
129  Model deployment pipeline fails at Docker buil...        Software issue
183  IT Training Request Requesting training sessio...  Purchase requisition
174  Keyboard Not Responding The printer driver nee...        Software issue
122  Installation for Linux Dear, during the meetin...        Software issue

[135 rows x 2 columns]

In [68]:
X_train[0]

'Employee Data Access Request An employee has requested access to their personal data stored in our systems. Please provide them with the requested information in compliance with data '

Well... 

Now start the data processing using NLP techniques!

We need to get some tools to help us.

We will continue in the tickets_classification2 notebook.